### ISSUE TITLE
How about the inference speed?

### ISSUE THREAD

**Issue by zyl1336110861** [dvlab-research/VFF#1]
@yanwei-li Thank you so much for your sharing! I am reading your paper now. I am curious about your model's inference speed.

**Comment by yanwei-li** [comment]
Hi, the inference varies a lot with different ray constructors, which brings cost. Here we provide a naive solution [here]( https://github.com/dvlab-research/VFF/blob/1e95c52d0bf35c872cde9227e9ab4fcdb1fd7fdb/pcdet/models/backbones_3d/vfe/image_vfe_modules/f2v/point_to_image_projection.py#L178). For a more efficient one, the ray can be constructed from the image. In this manner, the whole process cost around 200ms based on PVRCNN (120ms) in V100.

**Comment by zyl1336110861** [comment]
@yanwei-li OK! Thanks for your patience. So It is very hard to make it real-time on some devices such as Xavier.
