### ISSUE TITLE
About 2D pretrained model

### ISSUE THREAD

**Issue by yeminglang** [dvlab-research/VFF#11]
Thanks for your excellent work! I notice that 2D pretrained deeplabv3 model on coco dataset is applied.  I wonder if you have tested the model with the 2D pretrained model on Cityspaces dataset? Do you think it may lead to better performance? Thanks!
Looking for your reply!

**Comment by yanwei-li** [comment]
Hi, thanks for your interest. I haven't tried Cityscapes dataset. But I guess it may not bring too much gain. And it seems basic context could be enough for the 3D network.

**Comment by yeminglang** [comment]
Thanks for your reply!
