### ISSUE TITLE
python3 train.py --cfg_file cfgs/kitti_models/VFF_PVRCNN.yaml

### ISSUE THREAD

**Issue by liyemomo** [dvlab-research/VFF#2]
when I run python3 train.py --cfg_file cfgs/kitti_models/VFF_PVRCNN.yaml, there is an error that: 
File "VFF/pcdet/utils/transform_utils.py", line 44, in project_to_image
    points_depth = points_t[..., -1] - raw_project[..., 2, 3]
RuntimeError: The size of tensor a (1760) must match the size of tensor b (2) at non-singleton dimension 1
I don't know how to fix it.

**Comment by Rtakaha** [comment]
I fixed this problem by reshaping.

```python
points_depth = points_t[..., -1] - raw_project[..., 2, 3].reshape(points_t.shape[0], 1)
```

**Comment by liyemomo** [comment]
@Rtakaha Thank you for your advice.
But it doesn't work for me. I met this error again after reshaping.

File "VFF/pcdet/utils/transform_utils.py", line 44, in project_to_image
points_depth = points_t[..., -1] - raw_project[..., 2, 3].reshape(points_t.shape[0], 1)
RuntimeError: The size of tensor a (1600) must match the size of tensor b (2) at non-singleton dimension 2

Can you share your environment and how you built this project? 

My environment: 
Ubuntu 20.04 
pytorch 1.7.1 
CUDA 11.0 
spconv1.2.1
python 3.8.10
gcc 9.4.0

**Comment by wistful-8029** [comment]
I met this error too

**Comment by wistful-8029** [comment]
@liyejlu You try this sentence:  points_depth = points_t[..., -1] - raw_project[..., 2, 3].unsqueeze(dim=1)
