### ISSUE TITLE
UnboundLocalError: local variable 'mv_height' referenced before assignment

### ISSUE THREAD

**Issue by zijianh4** [dvlab-research/VFF#3]
Hi,
Thanks for your great work. However, I meet with some problems when trying training a model by myself. Which is shown as below
<img width="962" alt="image" src="https://user-images.githubusercontent.com/36258633/186787764-344224b6-aa7d-42d4-8d32-9a7a9b3a91e5.png">
I prepared the dataset exactly the same way, although I set `USE_ROAD_PLANE: False` for my training. Is there something that I miss, or `USE_ROAD_PLANE` must be `True`? Thanks!

**Comment by Fragilesky** [comment]
@zijianh4  Hello , I also set "USE_ROAD_PLANE: False" then meet this problem, have you solved this problem now?

**Comment by zijianh4** [comment]
> @zijianh4 Hello , I also set "USE_ROAD_PLANE: False" then meet this problem, have you solved this problem now?

Hi @Fragilesky ,
Yes, I have figured it out. Basically, you can refer to this solution: https://github.com/dvlab-research/FocalsConv/issues/8 :)

**Comment by Fragilesky** [comment]
Thank you for your reply! the suggest issue shows that updated database_sampler.py in line 404, and I notice there has "mv_height = mv_height[valid_mask]" under the line 404, I also add this code to my database_sampler.py under the line 311, but it's still no work, do you know the specific the line or some other changes?

**Comment by Fragilesky** [comment]
I solved this problem, thanks!
