### ISSUE TITLE
More details about the training implementation

### ISSUE THREAD

**Issue by xxxxhh** [dvlab-research/VFF#5]
Hi, thanks for your neat and valuable work! By the way, I would like to know about the training batch size for KITTI and Waymo. 

According to the paper, it seems that the batch_size for PV-RCNN on KITTI and Waymo are set as 8 and 64 respectively. I would like to make sure these parameters are right as I can not find them in the configuration files. 

By the way, have you tested the influence of batch size on KITTI or Waymo?

**Comment by xxxxhh** [comment]
Moreover, have you used the road map data for KITTI dataset?

**Comment by yanwei-li** [comment]
Hi, I use Batch 8 for KITTI (without using road map) and do not perform experiments on Waymo dataset. And I do not test other batch size for experiments.

**Comment by xxxxhh** [comment]
Got that, thanks!

**Comment by xxxxhh** [comment]
> Hi, I use Batch 8 for KITTI (without using road map) and do not perform experiments on Waymo dataset. And I do not test other batch size for experiments.

So, you've also set batch size as 8 for all experiments. Right?

**Comment by xxxxhh** [comment]
Table 9.

**Comment by xxxxhh** [comment]
> Hi, I use Batch 8 for KITTI (without using road map) and do not perform experiments on Waymo dataset. And I do not test other batch size for experiments.

For the result in Table 9, it that model trained with road map info leveraged? Actually, I failed to reproduce that performance without using road map even if I eval all the ckpts from epoch1 to epoch80 considering that the performance deviation may exist. Instead, when I use the road map info (by enabling it in the config file), I can get a slightly-lower but similar result as stated in Table 9.

**Comment by xxxxhh** [comment]
By the way, I notice that the "road map" is always set as "True" in the configuration files given in this repo. So I would like to  check whether the road map info is used for the experiments listed in your main paper. Thanks!

**Comment by yanwei-li** [comment]
Sorry for the late reply. I didn't find the response updated here. I checked the code and did not find the "road map" in the config. Can you point out what the "road map" is for me?

**Comment by xxxxhh** [comment]
Oh, I mean the "ROAD_PLANE" configuration parameter. For example, the one in the config file below.

https://github.com/dvlab-research/VFF/blob/1e95c52d0bf35c872cde9227e9ab4fcdb1fd7fdb/tools/cfgs/kitti_models/VFF_VoxelRCNN.yaml#L21

**Comment by yanwei-li** [comment]
Hi, this is only used to put the sampled GT instance into the current scenes, like that in https://github.com/dvlab-research/VFF/blob/54ff6ef470d0bfbe0dda0c2598ba31e12dfcf7a8/pcdet/datasets/augmentor/database_sampler.py#L205

**Comment by xxxxhh** [comment]
Got that, thanks! I have another question for you. If I would like to use the DB-sampler on the NuScenes dataset, how can I get the road_plane info? Could you give me any suggestion on that? Thanks!

**Comment by yanwei-li** [comment]
Hi, maybe you can refer to this [repo](https://github.com/dvlab-research/UVTR). I implement the cross-modality DB sampler for nuScenes dataset.

**Comment by xxxxhh** [comment]
Got that, thanks!
