### ISSUE TITLE
Request for visualization on  KITTI 3D OD

### ISSUE THREAD

**Issue by xxxxhh** [dvlab-research/VFF#6]
Could you provide some suggestions on the visualization on KITTI 3D object detection? Specifically, is there any useful related visualization repos ? : )

**Comment by yanwei-li** [comment]
Hi, maybe you can try the vis tools in OpenPCDet (https://github.com/open-mmlab/OpenPCDet/blob/master/tools/demo.py). I conduct visualization based on this repo.

**Comment by xxxxhh** [comment]
Got it, thanks!
